export const USER_SIGN_UP = 'USER_SIGN_UP';


export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_IN_PROGRESS = 'LOGIN_USER_IN_PROGRESS'
export const USER_LOGGED_OUT='USER_LOGGED_OUT'